# Generated by Django 5.2.10 on 2026-01-31 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_alter_room_sharing_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('id_proof_type', models.CharField(max_length=50)),
                ('id_proof_number', models.CharField(max_length=50)),
                ('worker_type', models.CharField(choices=[('caretaker', 'Caretaker'), ('cleaning', 'Cleaning Staff'), ('security', 'Security Guard'), ('cook', 'Cook'), ('maintenance', 'Maintenance Staff'), ('manager', 'Branch Manager'), ('other', 'Other')], max_length=20)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract')], default='full_time', max_length=20)),
                ('joining_date', models.DateField()),
                ('leaving_date', models.DateField(blank=True, null=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('daily', 'Daily'), ('hourly', 'Hourly')], default='monthly', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('resigned', 'Resigned'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=15)),
                ('emergency_contact_relation', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='workers/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='core.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkerAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('leave', 'On Leave')], max_length=20)),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='workers.worker')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WorkerLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('sick', 'Sick Leave'), ('casual', 'Casual Leave'), ('earned', 'Earned Leave'), ('unpaid', 'Unpaid Leave'), ('emergency', 'Emergency Leave')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='workers.worker')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkerSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('cheque', 'Cheque')], max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partial'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to='workers.worker')),
            ],
            options={
                'ordering': ['-month'],
            },
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['branch', 'status'], name='workers_wor_branch__7e198e_idx'),
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['worker_type'], name='workers_wor_worker__cf7bc9_idx'),
        ),
        migrations.AddIndex(
            model_name='workerattendance',
            index=models.Index(fields=['worker', 'date'], name='workers_wor_worker__542e7b_idx'),
        ),
        migrations.AddIndex(
            model_name='workerattendance',
            index=models.Index(fields=['date'], name='workers_wor_date_a25cb7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workerattendance',
            unique_together={('worker', 'date')},
        ),
        migrations.AddIndex(
            model_name='workerleave',
            index=models.Index(fields=['worker', 'status'], name='workers_wor_worker__aefcfa_idx'),
        ),
        migrations.AddIndex(
            model_name='workerleave',
            index=models.Index(fields=['start_date', 'end_date'], name='workers_wor_start_d_cfe8fd_idx'),
        ),
        migrations.AddIndex(
            model_name='workersalary',
            index=models.Index(fields=['worker', 'month'], name='workers_wor_worker__dbf4f8_idx'),
        ),
        migrations.AddIndex(
            model_name='workersalary',
            index=models.Index(fields=['payment_status'], name='workers_wor_payment_a70e4d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workersalary',
            unique_together={('worker', 'month')},
        ),
    ]
