# Generated by Django 5.2.5 on 2025-08-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_branch_options_alter_rentpayment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='amenities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='branch',
            name='established_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='has_ac',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branch',
            name='has_laundry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branch',
            name='has_mess',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branch',
            name='has_parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branch',
            name='has_security',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branch',
            name='has_wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branch',
            name='license_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='branch',
            name='nearby_facilities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='property_type',
            field=models.CharField(choices=[('ladies_hostel', 'Ladies Hostel'), ('mens_hostel', 'Mens Hostel'), ('mixed_hostel', 'Mixed Hostel'), ('guest_house', 'Guest House'), ('pg', 'Paying Guest')], default='ladies_hostel', max_length=20),
        ),
        migrations.AddField(
            model_name='branch',
            name='rules_and_regulations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='total_floors',
            field=models.IntegerField(default=1),
        ),
    ]
