# Generated by Django 5.2.3 on 2025-11-08 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_family_info_to_tenant'),
        ('core', '0005_userprofile_firebase_uid_userprofile_phone_verified_and_more'),
    ]

    operations = [
    ]
