# Generated by Django 5.2.3 on 2026-01-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20251108_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='sharing_type',
            field=models.IntegerField(blank=True, choices=[(1, '1-Sharing'), (2, '2-Sharing'), (3, '3-Sharing'), (4, '4-Sharing'), (5, '5-Sharing'), (6, '6-Sharing'), (7, '7-Sharing'), (8, '8-Sharing')], null=True),
        ),
    ]
